### ISSUE TITLE
Standalone interpreter

### ISSUE THREAD

**Issue by eush77** [adrianton3/befunjit#1]
Command line interface is a must-have for a language interpreter. Are there any plans for building a CLI?

With npm, it can be rather simple to build a standalone binary:
- [ ] Convert modules to CommonJS format.
- [ ] Add `package.json` file and declare dependencies (such as `coffee-script` or `jasmine`).
- [ ] Add a build step for visualizer using Browserify (or WebPack).
- [ ] Add CLI entry point.

**Comment by adrianton3** [comment]
Yes, support for node and a CLI are coming as well as partitioning everything in modules

**Comment by adrianton3** [comment]
befunjit is node friendly and has a cli now: `node build/befunjit.node.js [--lazy] [--time] <source>`
